# Generated by Django 5.1.7 on 2026-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('trip_started', 'Trip Started'), ('trip_delay', 'Trip Delay'), ('seat_assigned', 'Seat Assigned'), ('line_change', 'Line Change'), ('incident', 'Incident'), ('assignment_conflict', 'Assignment Conflict'), ('capacity_warning', 'Capacity Warning'), ('general', 'General'), ('student_report_submitted', 'Student Report Submitted'), ('student_line_changed', 'Student Line Changed'), ('report_resolved', 'Report Resolved')], default='general', max_length=30),
        ),
    ]
