# Generated by Django 5.1.7 on 2026-05-02 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driver_password_plain'),
        ('notifications', '0002_add_manager_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.driver'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('trip_started', 'Trip Started'), ('trip_delay', 'Trip Delay'), ('seat_assigned', 'Seat Assigned'), ('line_change', 'Line Change'), ('incident', 'Incident'), ('assignment_conflict', 'Assignment Conflict'), ('capacity_warning', 'Capacity Warning'), ('general', 'General'), ('student_report_submitted', 'Student Report Submitted'), ('student_line_changed', 'Student Line Changed'), ('report_resolved', 'Report Resolved'), ('manager_driver_update', 'Manager Driver Update')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.student'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('driver__isnull', True), ('student__isnull', False)), models.Q(('driver__isnull', False), ('student__isnull', True)), _connector='OR'), name='notification_student_xor_driver'),
        ),
    ]
