# Generated by Django 5.1.7 on 2026-04-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='show_on_manager_dashboard_alerts',
            field=models.BooleanField(default=False, help_text='If true, unresolved incident may appear in manager dashboard Pending Alerts.'),
        ),
    ]
