# Generated by Django 5.1.7 on 2026-05-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_line_optional_trip'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incident',
            name='incident_trip_or_line_required',
        ),
    ]
