# Generated by Django 5.1.7 on 2026-04-25 21:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_add_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('delay', 'Delay'), ('incident', 'Incident'), ('inquiry', 'General Inquiry'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Student Report',
                'verbose_name_plural': 'Student Reports',
                'db_table': 'student_reports',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
