# Generated by Django 5.1.7 on 2026-04-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('TransportManager', 'Transport Manager'), ('Student', 'Student')], default='TransportManager', max_length=20),
        ),
    ]
